name: C/C++ CI

on:
  push:
    branches: [ "main", "optimize-algorithm" ]
  pull_request:
    branches: [ "main", "optimize-algorithm" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CUDA_TOOLKIT_ROOT_DIR: /usr/local/cuda

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
    - name: Setup CUDA
      run: |
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo sh -c 'echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
        sudo apt-get update
        sudo apt-get install -y cuda
    - name: Build
      run: mkdir build && cd build && cmake .. && make
    - name: Test
      run: cd build && ctest
    - name: Check for GPU availability
      run: |
        if command -v nvidia-smi &> /dev/null
        then
          echo "GPU is available"
        else
          echo "GPU is not available"
        fi
    - name: Check for CUDA installation
      run: |
        if [ -d "/usr/local/cuda" ]
        then
          echo "CUDA is installed"
        else
          echo "CUDA is not installed"
        fi
